version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: dopwc_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dopwc_network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: dopwc_wordpress
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('SCRIPT_DEBUG', true);
        @ini_set('display_errors', 0);
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - dopwc_network

volumes:
  db_data:
  wordpress_data:

networks:
  dopwc_network:
    driver: bridge

